#reset AMPL
reset;

# Define the decision variables
var lemonade >= 0;
var iced_tea >= 0;

# Define the objective function
maximize profit: 1.5*lemonade + iced_tea;

# Define the constraints
subject to lemon_constraint: lemonade <= 10;
subject to tea_bag_constraint: iced_tea <= 8;
subject to sugar_constraint: 2*lemonade + iced_tea <= 20;

#solve
solve;

#display solution
display lemonade, iced_tea, profit;